### ISSUE TITLE
请在此申明正在翻译的部分以避免重复翻译

### ISSUE THREAD

**Issue by forsaken628** [screeps-cn/docs#22]
没有权限没办法修改projects，所以还是在issue里认领比较好。

**Comment by forsaken628** [comment]
API/ConstructionSite.md

**Comment by luke-cheng** [comment]
invaders.md
by 0c0大魔王
状态：完成
ayoitsLuke 临时代声明
源：Project

**Comment by forsaken628** [comment]
还是建议先提草案pr把这样进度大家都能看到

**Comment by HoPGoldy** [comment]
文档内容已完成汉化，故此 issue 关闭
