### ISSUE TITLE
翻译的文档被覆盖？

### ISSUE THREAD

**Issue by luke-cheng** [screeps-cn/docs#27]
见图：
![Capture](https://user-images.githubusercontent.com/40584729/57962971-b9b7f800-78eb-11e9-86f3-1ca466e9ffc6.PNG)
但 github.io 上并没被翻译
https://screeps-cn.github.io/invaders.html
我不懂 version control ，有懂的帮忙查下

**Comment by LokiSharp** [comment]
我之前的 Travis CI 设置是博客里复制来的，没有考虑多人协作 PR 的问题，导致任何 PR 都会更新页面，最新的我更新了判断是否为 PR。
但是之前 fork 了的没有和原 Repo 同步，导致这个没有生效。

**Comment by forsaken628** [comment]
[91069ae](https://github.com/screeps-cn/docs/commit/91069aef30b617e5203c95a3f7bd698e17570733)
搞定了
