### ISSUE TITLE
[可能的翻译错误或官方文档错误]移动力判定不是四舍五入原则

### ISSUE THREAD

**Issue by Leo-Mu** [screeps-cn/docs#67]
[移动力](https://screeps-cn.github.io/creeps.html#%E7%A7%BB%E5%8A%A8%E5%8A%9B)章节中最后一行写为

>Creep [TOUGH, ATTACK, ATTACK, MOVE, MOVE] 根据四舍五入原则 2 个 tick 移动 1 格。

对应[英文文档](https://docs.screeps.com/creeps.html#Movement)写为

>Creep [TOUGH, ATTACK, ATTACK, MOVE, MOVE] will move 1 square per 2 ticks because of rounding up.

我并不清楚这个英文文档中的 rounding up 到底指的是什么意思， Google translator 说它是四舍五入。
但如果我没理解错的话移动力的判定应当是按照部件生成疲劳值后每 tick 减去两倍 MOVE 部件数量，直至小于等于零，进行移动，移动后重新生成疲劳值。
效果即为向上取整而非四舍五入。

**Comment by forsaken628** [comment]
这个理解与游戏逻辑是一致的，没问题。不过字面表达是向上取整还是向下取整，可以再润色一下。

**Comment by HoPGoldy** [comment]
已由 [PR 69](https://github.com/screeps-cn/docs/pull/69) 修改为向上取整。
